### ISSUE TITLE
Promote tags to GitHub releases

### ISSUE THREAD

**Issue by aubelsb2** [apache/camel-quarkus#2864]
I am only subscribed to github release notifications:
![image](https://user-images.githubusercontent.com/20219956/124045962-323e8c00-da54-11eb-975c-b86b15a116cf.png)

However it seems that simply tagging the release isn't enough to trigger a release:
![image](https://user-images.githubusercontent.com/20219956/124045990-44b8c580-da54-11eb-8cea-9f798de45793.png)

If you edit a tag and go: "publish release" it will publish:
![image](https://user-images.githubusercontent.com/20219956/124046069-70d44680-da54-11eb-9863-707e947e22ea.png)

However you should be able to do this from a github action too. A quick google suggests that this might work:
```
name: Main

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```
