### ISSUE TITLE
camel-quarkus-openapi-java marking all properties as type object in native mode

### ISSUE THREAD

**Issue by mbchangellc** [apache/camel-quarkus#3606]
When running a native image in a Docker container, the types of all properties in the generated openapi document are of type object.  When run with the JVM/non-native, properties are correctly marked as type string.  Project reproducing the issue attached.

Excerpt generated running as native application in Docker container:
```
components:
  schemas:
    Fruit:
      type: "object"
      properties:
        name:
          type: "object"
        description:
          type: "object"
```

Excerpt generated running with the JVM:
```
components:
  schemas:
    Fruit:
      type: "object"
      properties:
        name:
          type: "string"
        description:
          type: "string"
```

Build command
`/gradlew clean build -Dquarkus.package.type=native -Dquarkus.native.container-build=true -Dquarkus.container-image.build=true`

Environment:
macOS 12.2.1, Oracle JDK 11.0.12, ubi-quarkus-native-image 21.3-java11, Quarkus 2.7.3.Final

Same behavior using JDK 17 and ubi-quarkus-mandrel:22.0.0.2-Final-java17

[camel-openapi-types-bug.zip](https://github.com/apache/camel-quarkus/files/8216012/camel-openapi-types-bug.zip)
