### ISSUE TITLE
[camel-quarkus-aws2-s3] Support path style access buckets

### ISSUE THREAD

**Issue by vladimirfx** [apache/camel-quarkus#4770]
We actively use internal S3 storage which can't be accessed with domain-style buckets. Please provide `path-style-access` configuration option:

```yaml
camel:
  component:
    aws2-s3:
      path-style-access: 'true'
#  ....
```
