### ISSUE TITLE
Error No consumers available on endpoint in Unit test with yaml routes

### ISSUE THREAD

**Issue by SirSkizo** [apache/camel-quarkus#4927]
Hello, I am having some problems when trying to test my camels routes in Quarkus `v2.16.6.Final`.

If a try to test the following route (defined as a yaml file):

``` yaml
  - route:
    id: my-route-id
    from:
      uri: direct:my-uir-id
      id: from-6ae3
      steps:
        - unmarshal:
            id: unmarshal-b88a
            json:
              id: json-5d60
              library: jackson
              useDefaultObjectMapper: false
              unmarshalType: my-custom-dto
        - to:
            uri: bean:my-java-bean
            id: to-0e55
    group: my-group
    messageHistory: true
    trace: true
    logMask: true
    startupOrder: 1
    autoStartup: true
    description: Bug time
```

And then I make a unit test like this:

```java
@QuarkusTest
public class MyRouteRouteTest extends CamelQuarkusTestSupport {

  private static final Logger LOG = Logger.getLogger(MyRouteRouteTest.class);

  @Test
  public void testRoute1() {

    // Read a json file as an string to simulate a kafka message
    final String sampleKafkaJsonStr = HelperFunctions
        .getStreamContents(HelperFunctions.getResourceAsStream("kafka-messages/my-mock.json"));

    // Apply the camel route to the previous input
    TpaeJiraSR routeResult = (DtoReturnType) this.template.requestBody("direct:my-uri-id", sampleKafkaJsonStr);

    // Perform the assertions
    Assertions.assertEquals(routeResult.field1, "Whatever");

  }

  // Copy and paste the same test
  @Test
  public void testRoute1Copy() {

    // Read a json file as an string to simulate a kafka message
    final String sampleKafkaJsonStr = HelperFunctions
        .getStreamContents(HelperFunctions.getResourceAsStream("kafka-messages/my-mock.json"));

    // Apply the camel route to the previous input
    TpaeJiraSR routeResult = (DtoReturnType) this.template.requestBody("direct:my-uri-id", sampleKafkaJsonStr);

    // Perform the assertions
    Assertions.assertEquals(routeResult.field1, "Whatever");

  }

}
``` 

If a run the tests. The second one fails with the following error:
`Caused by: org.apache.camel.component.direct.DirectConsumerNotAvailableException: No consumers available on endpoint: direct://my-uri-id. Exchange[]`.

So, when I use the same route in different tests, only the first test is executed without this error. I think that this is somehow related with the camel context since the test do recognize the test for the first time.

I have already try to  clean the context with `@TestProfile` as is mentioned [here](https://access.redhat.com/documentation/en-us/red_hat_integration/2023.q1/html-single/getting_started_with_camel_extensions_for_quarkus/index#cameltestsupport_style_of_testing) and also by injecting the camel context directly into the text.

I get to make my test work by translating the routes form yaml to java:

``` java
public class MyRoute extends RouteBuilder {

  @Override
  public void configure() throws Exception {
    from("direct:my-route-uri-2")
        .group("my-group")
        .messageHistory()
        .tracing()
        .logMask()
        .startupOrder(1)
        .autoStartup(true)
        .routeDescription("Bug Time")
        .routeId("my-route-id")
        .unmarshal().json(JsonLibrary.Jackson, MyDto.class)
        .to("bean:MyClassBean")
        .to("log:result");
  }
}
```

And then, in the test, I needed to override the Route builder in order to include the route:

```java
@QuarkusTest
public class MyRouteRouteTest extends CamelQuarkusTestSupport {

  private static final Logger LOG = Logger.getLogger(MyRouteRouteTest.class);
  @Override
  protected RoutesBuilder createRouteBuilder() {
    return new MyRoute();
  }
```

And then everything works fine. 

It can be something related to the `CamelQuarkusTestSupport`? . Let my know if you need all my dependencies
