### ISSUE TITLE
Camel 4.9 - Add support for startup condition

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-quarkus#6664]
### Describe the feature here

https://issues.apache.org/jira/browse/CAMEL-21353

Here is how it was added to camel-spring-boot
https://github.com/apache/camel-spring-boot/commit/ab83d59c377abdf977a03b0944e408837c4af758

And this jbang example should be able to export and run on CEQ
```
camel.startupcondition.enabled = true
camel.startupcondition.environment-variable-exists = FOO_BAR
camel.startupcondition.timeout = 60000
camel.main.name = dude
```

And the yaml route
```
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - setBody:
          simple: "Hello Camel from ${routeId}"
      - log: "${body}"
     
```
