### ISSUE TITLE
Unexpected route discovery behavior when "mixing" `routes-discovery.include-patterns` and bean scopes

### ISSUE THREAD

**Issue by x80486** [apache/camel-quarkus#6882]
### Bug description

I think there may be an (unintended) issue regarding route discovery :thinking:

I configured `quarkus.camel.routes-discovery.include-patterns` setting to control which routes should be discovered:

```yaml
quarkus:
  camel:
    routes-discovery:
      enabled: true
      include-patterns:
        - tld/domain/route/* # Routes defined in tld.domain.route package
```

With this configuration, I would expect that no routes, other than the ones defined in `include-patterns`, will be discovered. This works fine as long as there aren't any `RouteBuilder` classes with bean-scoped annotations — they will be included as well, regardless of the aforementioned settings.

Is this behavior intended, or could it be considered a bug? I was under the assumption that `include-patterns` will strictly limit the discovery.

I have reviewed the documentation but could not find any specific mention of this behavior.
